enhancement: dynamic example and distinct role definition name
Azure/terraform-azurerm-avm-ptn-alz pull request #21
Opened 2023-12-11 14:08 UTC by jaredfholgate

This PR adds two enhancements:

1. It adds a post-fix to the role definition names to avoid clashes during testing or for real world scenarios.
2. It adds an end to end sample for using the module with a dynamically defined management group structure using a yaml file.

2023-12-11 14:45 UTC, jaredfholgate commented
@matt-FFFFFF If you'd like me to get the E2E tests working (with a Ready to Test label setup), let me know.

2023-12-11 15:14 UTC, matt-FFFFFF requested changes
couple of files need removing, otherwise excellent!

2023-12-11 15:14 UTC, matt-FFFFFF commented on examples/dynamic-input/header.md
This file is not required

2023-12-11 15:14 UTC, matt-FFFFFF commented on examples/dynamic-input/footer.md
This file is not required

2023-12-11 18:39 UTC, matt-FFFFFF commented
> @matt-FFFFFF If you'd like me to get the E2E tests working (with a Ready to Test label setup), let me know.

That would be very useful I think feel free!

2023-12-11 18:58 UTC, jaredfholgate commented on examples/dynamic-input/footer.md
Should I remove these files from the other example too?

2023-12-11 20:26 UTC, jaredfholgate commented
> > @matt-FFFFFF If you'd like me to get the E2E tests working (with a Ready to Test label setup), let me know.
> 
> That would be very useful I think feel free!

Tests are running now. There is a chance they will hit timing issue and will need to adjust the waits in the example. This is based on my experience earlier today.

2023-12-21 15:56 UTC, matt-FFFFFF commented
awesome work @jaredfholgate LGTM

2023-12-21 15:57 UTC, matt-FFFFFF approved these changes

2023-12-21 15:57 UTC, merged